#!/bin/bash

I2CGET=/usr/sbin/i2cget

calculate_data_adv()
{
	h2="$I2CGET -y -f 2 $1 $2"
	h2=`eval $h2`
	h1="$I2CGET -y -f 2 $1 $3"
	h1=`eval $h1`
	h1_1=${h1:2:2}
	h1_2=${h2:2:2}
	echo "$4: $((16#$h1_2$h1_1)) [$h1_2 $h1_1]"
	result=$((16#$h1_2$h1_1))
}

# WIDTH ***********************************
#TOTAL_LINE_WIDTH[13:0], Addr 68 (HDMI), Address 0x1E[5:0]; Address 0x1F[7:0] (Read Only)
calculate_data_adv 0x34 0x1e 0x1f TOTAL_LINE_WIDTH
tlw=$result

#LINE_WIDTH[12:0], Addr 68 (HDMI), Address 0x07[4:0]; Address 0x08[7:0] (Read Only)
calculate_data_adv 0x34 0x07 0x08 LINE_WIDTH
lw=$result

#HSYNC_FRONT_PORCH[12:0], Addr 68 (HDMI), Address 0x20[4:0]; Address 0x21[7:0] (Read Only)
calculate_data_adv 0x34 0x20 0x21 HSYNC_FRONT_PORCH
hfp=$result

#HSYNC_PULSE_WIDTH[12:0], Addr 68 (HDMI), Address 0x22[4:0]; Address 0x23[7:0] (Read Only)
calculate_data_adv 0x34 0x22 0x23 HSYNC_PULSE_WIDTH
hpw=$result

#HSYNC_BACK_PORCH[12:0], Addr 68 (HDMI), Address 0x24[4:0]; Address 0x25[7:0] (Read Only)
calculate_data_adv 0x34 0x24 0x25 HSYNC_BACK_PORCH
hbp=$result

#BG_LINE_WIDTH[12:0], Addr 68 (HDMI), Address 0xE2[4:0]; Address 0xE3[7:0] (Read Only)
calculate_data_adv 0x34 0xe2 0xe3 BG_LINE_WIDTH
blw=$result



# HEIGHT ***********************************
#FIELD0_TOTAL_HEIGHT[13:0], Addr 68 (HDMI), Address 0x26[5:0]; Address 0x27[7:0] (Read Only)
calculate_data_adv 0x34 0x26 0x27 FIELD0_TOTAL_HEIGHT
fth=$result

#FIELD0_HEIGHT[12:0], Addr 68 (HDMI), Address 0x09[4:0]; Address 0x0A[7:0] (Read Only)
calculate_data_adv 0x34 0x09 0x0a FIELD0_HEIGHT
fh=$result

#FIELD0_VS_FRONT_PORCH[13:0], Addr 68 (HDMI), Address 0x2A[5:0]; Address 0x2B[7:0] (Read Only)
calculate_data_adv 0x34 0x2a 0x2b FIELD0_VS_FRONT_PORCH
ffp=$result

#FIELD0_VS_PULSE_WIDTH[13:0], Addr 68 (HDMI), Address 0x2E[5:0]; Address 0x2F[7:0] (Read Only)
calculate_data_adv 0x34 0x2e 0x2f FIELD0_VS_PULSE_WIDTH
fpw=$result

#FIELD0_VS_BACK_PORCH[13:0], Addr 68 (HDMI), Address 0x32[5:0]; Address 0x33[7:0] (Read Only)
calculate_data_adv 0x34 0x32 0x33 FIELD0_VS_BACK_PORCH
fbp=$result
