#!/bin/bash

# vlog-tools
DIR_VT_HOME="home"
DIR_VT_MOTION="motion"

# return
RET=1

# Install HOME data
DIR=$DIR_VT_HOME
if [ -d "$DIR" ]; then
  echo -e "\nInstalling home data files"
  cp $DIR/vlog /usr/local/bin/vlog
  echo -e "#vlog.conf file \nDIR_VT=${PWD}\nREMOTE=\"dgomez@192.168.2.83:\"\nEDID_EN=1\n" | tee /usr/local/bin/vlog.conf
  ln -fs /usr/local/bin/vlog ${HOME}/vlog
  ln -fs /usr/local/bin/vlog.conf ${HOME}/vlog.conf
  echo -e "#.bash_aliases file\nsource /usr/local/bin/vlog\n" | tee ${HOME}/.bash_aliases
else
  echo -e "\nImpossible to install $DIR"
  RET=0
fi


# Install MOTION data
DIR=$DIR_VT_MOTION
if [ -d "$DIR" ]; then
  echo -e "\nInstalling $DIR data files"
  cp $DIR/motion.conf /usr/local/etc/motion/motion.conf
else
  echo -e "\nImpossible to install $DIR"
  RET=0
fi

# Check installation
if [ $RET == 1 ]; then
  echo -e "\nInstallation completed. Exit"
  exit 
  exit 0
  exit 1
else
  echo -e "\nInstallation error. Please execute INSTALL in the same directory"
fi
